version: '3.5'
services:
  notd:
    build: .
    container_name: notd
    volumes:
      - ./ServerSettings.ini:/home/steam/notd/LF/Saved/Config/ServerSettings.ini        
      - ./Saved:/home/steam/notd/LF/Saved:rw
      - ./backup:/home/steam/backup:rw
      - ./backup.sh:/home/steam/notd/backup.sh
    ports:
      - 7777:7777/udp
      - 27015:27015/udp
    restart: unless-stopped
    tty: true
