version: '3.5'
services:
  notd:
    build: .
    container_name: notd
    environment:
      TZ: "Europe/Moscow"
    volumes:
          
      - ./gamedata:/home/steam/notd:rw
      - ./ServerSettings.ini:/home/steam/ServerSettings.ini 
      - ./backup:/home/steam/backup:rw
      - ./start.sh:/etc/entrypoint.sh
      - ./backup.sh:/home/steam/backup.sh
      - ./crontab.txt:/home/steam/crontab.txt
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7777:7777/udp
      - 27015:27015/udp
    restart: unless-stopped
    tty: true
