version: '3.5'
services:
  notd:
    build: .
    container_name: notd
    volumes:
      - ./Saved:/home/steam/notd/LF/Saved
      - ./ServerSettings.ini:/home/steam/notd/LF/Saved/Config/ServerSettings.ini
      - ./backup:/home/steam/backup
    ports:
      - 7777:7777/udp
      - 27015:27015/udp
    restart: unless-stopped
    tty: true
